name: Sync DAGs to Airflow in Codespace

on:
  push:
    paths:
      - 'airflow/dags/**'
      - 'reload_dags.sh'
    branches:
      - main

jobs:
  reload-dags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Recargar DAGs dentro de Codespace
        run: bash reload_dags.sh
